-- ============================================================
-- TABLES RAW - Zone d'atterrissage JSON (1 colonne VARIANT)
-- Alimentées par Snowpipe via COPY INTO
-- ============================================================

CREATE OR REPLACE TABLE FRANCE_EMPLOI_DB.STAGING.CHOMEURS_INDEMNISES_RAW (
    raw_data VARIANT
);

CREATE OR REPLACE TABLE FRANCE_EMPLOI_DB.STAGING.DEMANDEURS_EMPLOI_TRANCHE_AGE_RAW (
    raw_data VARIANT
);

CREATE OR REPLACE TABLE FRANCE_EMPLOI_DB.STAGING.OFFRES_EMPLOI_FRANCE_TRAVAIL_RAW (
    raw_data VARIANT
);

CREATE OR REPLACE TABLE FRANCE_EMPLOI_DB.STAGING.TRANCHE_AGE_RAW (
    raw_data VARIANT
);


-- ============================================================
-- PIPES - Ingestion automatique GCS → RAW via Pub/Sub
-- AUTO_INGEST = TRUE : déclenché par notification GCS
-- PATTERN : exclut les fichiers .keep créés par Terraform
-- ============================================================

CREATE OR REPLACE PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_CHOMEURS_INDEMNISES
    AUTO_INGEST = TRUE
    INTEGRATION = 'NOTIF_CHOMEURS_INDEMNISES'
AS
    COPY INTO FRANCE_EMPLOI_DB.STAGING.CHOMEURS_INDEMNISES_RAW (raw_data)
    FROM (SELECT $1 FROM @FRANCE_EMPLOI_DB.PUBLIC.GCS_CHOMEURS_INDEMNISES_LOAD)
    PATTERN = '.*\\.json(\\.gz)?$';

CREATE OR REPLACE PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_DEMANDEURS_EMPLOI_TRANCHE_AGE
    AUTO_INGEST = TRUE
    INTEGRATION = 'NOTIF_DEMANDEURS_EMPLOI_TRANCHE_AGE'
AS
    COPY INTO FRANCE_EMPLOI_DB.STAGING.DEMANDEURS_EMPLOI_TRANCHE_AGE_RAW (raw_data)
    FROM (SELECT $1 FROM @FRANCE_EMPLOI_DB.PUBLIC.GCS_DEMANDEURS_EMPLOI_TRANCHE_AGE_LOAD)
    PATTERN = '.*\\.json(\\.gz)?$';

CREATE OR REPLACE PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_OFFRES_EMPLOI_FRANCE_TRAVAIL
    AUTO_INGEST = TRUE
    INTEGRATION = 'NOTIF_OFFRES_EMPLOI_FRANCE_TRAVAIL'
AS
    COPY INTO FRANCE_EMPLOI_DB.STAGING.OFFRES_EMPLOI_FRANCE_TRAVAIL_RAW (raw_data)
    FROM (SELECT $1 FROM @FRANCE_EMPLOI_DB.PUBLIC.GCS_OFFRES_EMPLOI_FRANCE_TRAVAIL_LOAD)
    PATTERN = '.*\\.json(\\.gz)?$';

CREATE OR REPLACE PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_TRANCHE_AGE
    AUTO_INGEST = TRUE
    INTEGRATION = 'NOTIF_TRANCHE_AGE'
AS
    COPY INTO FRANCE_EMPLOI_DB.STAGING.TRANCHE_AGE_RAW (raw_data)
    FROM (SELECT $1 FROM @FRANCE_EMPLOI_DB.PUBLIC.GCS_TRANCHE_AGE_LOAD)
    PATTERN = '.*\\.json(\\.gz)?$';


-- ============================================================
-- REFRESH - Charge les fichiers déjà présents dans GCS
-- À exécuter une fois après création des pipes
-- ============================================================

ALTER PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_CHOMEURS_INDEMNISES          REFRESH;
ALTER PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_DEMANDEURS_EMPLOI_TRANCHE_AGE REFRESH;
ALTER PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_OFFRES_EMPLOI_FRANCE_TRAVAIL  REFRESH;
ALTER PIPE FRANCE_EMPLOI_DB.PUBLIC.PIPE_TRANCHE_AGE                   REFRESH;


-- ============================================================
-- MONITORING - Vérification du statut des pipes
-- ============================================================

SELECT SYSTEM$PIPE_STATUS('FRANCE_EMPLOI_DB.PUBLIC.PIPE_CHOMEURS_INDEMNISES');
SELECT SYSTEM$PIPE_STATUS('FRANCE_EMPLOI_DB.PUBLIC.PIPE_DEMANDEURS_EMPLOI_TRANCHE_AGE');
SELECT SYSTEM$PIPE_STATUS('FRANCE_EMPLOI_DB.PUBLIC.PIPE_OFFRES_EMPLOI_FRANCE_TRAVAIL');
SELECT SYSTEM$PIPE_STATUS('FRANCE_EMPLOI_DB.PUBLIC.PIPE_TRANCHE_AGE');


-- ============================================================
-- CONTROLE - Vérification du contenu des tables RAW
-- Patienter qeuelque minutes aprés le pipe (le temps dépend de si vous utiliser votre propre warehouse ou celui proposé)
-- ============================================================

SELECT * FROM FRANCE_EMPLOI_DB.STAGING.CHOMEURS_INDEMNISES_RAW          LIMIT 10;
SELECT * FROM FRANCE_EMPLOI_DB.STAGING.DEMANDEURS_EMPLOI_TRANCHE_AGE_RAW LIMIT 10;
SELECT * FROM FRANCE_EMPLOI_DB.STAGING.OFFRES_EMPLOI_FRANCE_TRAVAIL_RAW  LIMIT 10;
SELECT * FROM FRANCE_EMPLOI_DB.STAGING.TRANCHE_AGE_RAW                   LIMIT 10;
